version: '3'
services:
  mysqldb:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: foodSystem123@
      MYSQL_DATABASE: foodsystem
      MYSQL_USER: foodsystemuser
      MYSQL_PASSWORD: foodSystem123@
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
          - mysqldb:/var/lib/mysql
    ports:
      - '8081:3306'
  spring-boot:
    image: foodsystem
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: foodsystem
    ports:
      - "8080:8080" 
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8:3306/foodsystem?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: foodsystemuser
      SPRING_DATASOURCE_PASSWORD: foodSystem123@
volumes:
  mysqldb: