insert into categoria values(1, 'Lanche');
insert into categoria values(2, 'Bebida');
insert into categoria values(3, 'Acompanhamento');
insert into categoria values(4, 'Sobremesa');
insert into status_pedido values(1, 'Pedido criado');
insert into status_pedido values(2,  'Aguardando preparação');
insert into status_pedido values(3, 'Preparando');
insert into status_pedido values(4, 'Finalizado');
insert into status_pedido values(5, 'Entregue');
insert into setor values(1, 'Cozinha');
insert into setor values(2,  'Recepcao');
insert into setor values(3, 'Entrega');
insert into setor values(4, 'Gerencia');
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (1,  "Hamburguer mac", "Hamburguer do mc Donalds", 1, 30.5, 1);
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (2,  "Hot Dog", "Pão de hamburger, salsicha, vinagrete ou tomate, pere e batata palha", 1, 15.0, 1);
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (3,  "Coca Cola", "Refrigerante de cola tradicional", 2, 8.0, 1);
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (4,  "Dolly Limão", "O melhor", 2, 6.0, 1);
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (5,  "Dolly Guarana", "O sabor brasileiro", 2, 6.0, 1);
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (6,  "Batata frita tradicional", "Batata frita com sal", 15, .0, 1);
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (7,  "Mini Pasteis", "Porção com 10 mini pasteis", 3, 20.0, 1);
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (8,  "Pudim", "Pedaço de pudim caseiro da casa", 4, 6.0, 1);
insert into produto (id_produto, nm_produto, nm_descricao_produto, id_categoria, db_valor, in_ativo) values (9,  "Bolo Gelado", "Pedaço de bolo gelado", 4, 7.0, 1);