insert into categoria values(1, 'Lanche');
insert into categoria values(2, 'Bebida');
insert into categoria values(3, 'Acompanhamento');
insert into categoria values(4, 'Sobremesa');
insert into status_pedido values(1, 'Pedido');
insert into status_pedido values(2,  'Aguardando preparação');
insert into status_pedido values(3, 'Preparando');
insert into status_pedido values(4, 'Finalizado');
insert into status_pedido values(5, 'Entregue');
insert into setor values(1, 'Cozinha');
insert into setor values(2,  'Recepcao');
insert into setor values(3, 'Entrega');
insert into setor values(4, 'Gerencia');